### ISSUE TITLE
EleventyConfigError: Error in your Eleventy config file

### ISSUE THREAD

**Issue by Tiberriver256** [qiwi/tech-radar#127]
## Issue type
* [x] bug report
* [ ] idea
* [ ] question
* [ ] other

## Expected behavior
Running `npx @qiwi/tech-radar --input ".\my-radar.json" --output /radar` should generate a report

## Actual behavior
I get the following error:

```
EleventyConfigError: Error in your Eleventy config file 'C:\Users\MyUser\AppData\Local\Temp\tech-radar-eeCfD\Xb7HQ\config.js'. You may need to run `npm install`.
```

* [x] I've read the docs. This case is not mentioned
* [x] Similar issue does not exist

## Specifications
- version: @qiwi/tech-radar@latest; node@v22.5.1
- platform: Windows
- ci: N/A

**Comment by defhid** [comment]
The problem is [here](https://github.com/qiwi/tech-radar/blob/4a065bc7d4e4f153382fdfdf3cb45d2b355342bb/src/main/js/generator/index.js#L15).
A written file is invalid because of backslashes used in Windows OS.
The **solution** is to wrap the path in JSON: ``` `require(${JSON.stringify(configExtPath)})` ```

**Comment by Tiberriver256** [comment]
Tested out `1.13.24` @antongolub.

Still getting this error:
```
EleventyConfigError: Error in your Eleventy config file 'C:\Users\[USERNAME]\AppData\Local\Temp\tech-radar-Vs8vx\AF4X_\config.js'. You may need to run `npm install`.
    at TemplateConfig.requireLocalConfigFile ([NPM_CACHE]\@11ty\eleventy\src\TemplateConfig.js:312:15)
    at TemplateConfig.mergeConfig ([NPM_CACHE]\@11ty\eleventy\src\TemplateConfig.js:334:28)
    at TemplateConfig.getConfig ([NPM_CACHE]\@11ty\eleventy\src\TemplateConfig.js:159:26)
    at new Eleventy ([NPM_CACHE]\@11ty\eleventy\src\Eleventy.js:109:39)
    at render (file:///[NPM_CACHE]/@qiwi/tech-radar/src/main/js/generator/index.js:140:16)
    at async genNavPage (file:///[NPM_CACHE]/@qiwi/tech-radar/src/main/js/generator/index.js:129:3)
    at async renderRadars (file:///[NPM_CACHE]/@qiwi/tech-radar/src/main/js/index.js:97:3)
```

Had 3.7 Sonnet Thinking, take a stab at guessing what's happening. This was its thought:

```

Let me help you triage this error. First, I'll examine the repository structure to understand what we're working with.

Ran tool
Let's check the package.json file to understand the project dependencies and configuration:

Read file: package.json
Now let's look at the Eleventy configuration file and the CLI file that's being executed:

Ran tool
Let me check for any Eleventy-related configuration files in the project:

Ran tool
Let's examine the generator file that initializes Eleventy, as it's the one referenced in the error stack trace:

Read file: src/main/js/generator/index.js
Let's check for the `.eleventy.cjs` file that's referenced in the generator:

Ran tool
Let's examine this file:

Read file: src/main/js/generator/.eleventy.cjs
Let's check the CLI file that's being executed:

Read file: src/main/js/cli.mjs
Now let's check the index.js file that's running the generator:

Read file: src/main/js/index.js
Based on the files I've examined, I can now identify the issue. Here's what's happening:

1. Your error occurs when running the tech-radar CLI on a Windows machine.
2. The error specifically mentions a problem with the Eleventy config file at a temporary path.
3. Looking at the code in `src/main/js/generator/index.js`, lines 12-22, there's a function `genConfig` that creates a temporary config file with the following content:
```js
module.exports = (config) => require('${configExtPath}')(Object.assign(config, ${JSON.stringify(configMixin)}))
```

4. The issue is in line 12 where it creates the path to the `.eleventy.cjs` file:
```js
const configExtPath = local.resolve(rootDir, 'generator/.eleventy.cjs')
```

5. The path handling uses this special code for Windows:
```js
const local = path[process.platform === 'win32' ? 'win32' : 'posix']
```

The root cause appears to be the path resolution in the config file. When the temporary config.js file is created, it's embedding a path that may have Windows-style backslashes, which leads to issues when that path is later used in a `require()` statement.

To fix this issue:

1. You need to make sure the paths in the generated config file are properly formatted for Windows.
2. The path resolution needs to be adjusted for Windows compatibility.

Try this solution:

```javascript:src/main/js/generator/index.js
// ... existing code ...
import path from 'node:path'
import Eleventy from '@11ty/eleventy'
import fse from 'fs-extra'
import { uniq } from 'lodash-es'

import { rootDir, tplDir } from '../constants.js'
import { tempDir } from '../util.js'
import { genMdAssets } from './markdown.js'

const local = path[process.platform === 'win32' ? 'win32' : 'posix']

export const genConfig = async ({ temp, output, prefix }) => {
  // Use path.resolve instead of local.resolve to ensure proper path resolution
  const configExtPath = path.resolve(rootDir, 'generator/.eleventy.cjs')
  const configMixin = { extra: { temp, prefix, output } }
  const configPath = path.join(temp, 'config.js')
  
  // Ensure the path uses forward slashes for require() by replacing backslashes
  const requirePath = configExtPath.replace(/\\/g, '/')
  
  const configContents = `
module.exports = (config) => require('${requirePath}')(Object.assign(config, ${JSON.stringify(
    configMixin,
  )}))
`
  await fse.outputFile(configPath, configContents, 'utf8')

  return configPath
}
// ... existing code ...
```
Now that I've fixed the issue, let me explain what was happening:

The error occurred because the Tech Radar CLI was failing to properly configure the Eleventy static site generator on Windows. The specific issue was in the path handling when generating a temporary configuration file for Eleventy.

Here's what was happening:

1. On Windows, the code was creating a config file with Windows-style backslashes in the path (e.g., `C:\path\to\file`).
2. When that path was used in a `require()` statement, the backslashes were being interpreted as escape characters, causing the path to be invalid.

The fix I implemented does two important things:

1. Uses `path.resolve()` instead of the custom `local.resolve()` to get a proper absolute path
2. Ensures the path is formatted with forward slashes by replacing any backslashes with forward slashes before inserting it into the generated config file

This ensures that when Eleventy tries to require the configuration file extension, it will use a properly formatted path that works on Windows.

To test this fix, try running the CLI again. It should now work correctly on your Windows machine without generating the Eleventy configuration error.
```

**Comment by antongolub** [comment]
Ok, let's try this approach:

https://github.com/qiwi/tech-radar/blob/43638840286891f59d43e4c296e970aed7802138/src/main/js/generator/index.js#L11-L20

**Comment by defhid** [comment]
@antongolub, it's working now, thanks!
